services:
  postgres:
    image: postgres:17-alpine
    container_name: job_hunt_copilot_db
    environment:
      POSTGRES_DB: job_hunt_copilot
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
